module.exports = {
  {
   "ScenarioId":"001001_ichika01",
   "AppearCharacters":[
      {
         "Character2dId":1,
         "CostumeType":"01ichika_normal"
      },
      {
         "Character2dId":2,
         "CostumeType":"02saki_normal"
      }
   ],
   "FirstLayout":[
      
   ],
   "FirstBgm":"bgm00018",
   "FirstBackground":"bg_a002201",
   "Snippets":[
      {
         "Action":6,
         "ProgressBehavior":1,
         "ReferenceIndex":0,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":1,
         "ReferenceIndex":0,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":0,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":1,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":1,
         "ReferenceIndex":1,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":1,
         "ReferenceIndex":2,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":0,
         "ReferenceIndex":3,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":2,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":3,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":4,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":4,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":5,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":6,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":7,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":5,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":8,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":6,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":9,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":7,
         "Delay":2.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":8,
         "Delay":4.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":10,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":11,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":9,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":12,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":10,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":13,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":11,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":14,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":15,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":12,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":16,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":17,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":18,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":13,
         "Delay":5.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":14,
         "Delay":9.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":19,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":20,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":15,
         "Delay":3.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":21,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":16,
         "Delay":5.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":22,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":17,
         "Delay":2.5
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":23,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":24,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":18,
         "Delay":4.0
      },
      {
         "Action":7,
         "ProgressBehavior":1,
         "ReferenceIndex":0,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":25,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":26,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":19,
         "Delay":3.0
      },
      {
         "Action":7,
         "ProgressBehavior":0,
         "ReferenceIndex":1,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":27,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":28,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":20,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":29,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":21,
         "Delay":5.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":30,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":22,
         "Delay":3.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":31,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":23,
         "Delay":4.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":32,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":24,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":33,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":25,
         "Delay":2.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":34,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":35,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":36,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":26,
         "Delay":3.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":37,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":27,
         "Delay":2.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":28,
         "Delay":6.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":38,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":29,
         "Delay":4.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":39,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":40,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":41,
         "Delay":0.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":42,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":30,
         "Delay":3.0
      },
      {
         "Action":1,
         "ProgressBehavior":1,
         "ReferenceIndex":43,
         "Delay":0.0
      },
      {
         "Action":4,
         "ProgressBehavior":0,
         "ReferenceIndex":31,
         "Delay":1.0
      },
      {
         "Action":7,
         "ProgressBehavior":1,
         "ReferenceIndex":2,
         "Delay":0.5099999904632568
      },
      {
         "Action":6,
         "ProgressBehavior":1,
         "ReferenceIndex":1,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":1,
         "ReferenceIndex":32,
         "Delay":0.0
      },
      {
         "Action":2,
         "ProgressBehavior":0,
         "ReferenceIndex":33,
         "Delay":0.0
      }
   ],
   "TalkData":[
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"窶ｦ窶ｦ莉頑律縺ｯ鬚ｨ縺梧ｰ玲戟縺｡縺�＞縺ｪ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_01_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"闃ｱ繧よｰ玲戟縺｡繧医＆縺昴≧縺ｫ謠ｺ繧後※縺ｦ窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-tilthead0506",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_02_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ゅ√＞縺｣縺｡繧�ｓ縺薙％縺ｫ縺�◆繧薙□�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_03_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"蜥ｲ蟶後√←縺�°縺励◆縺ｮ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-tilthead01",
               "FacialName":"face_surprise_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_04_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"謨吝ｮ､縺ｫ縺�↑縺九▲縺溘°繧峨―n縺ｩ縺薙↓陦後▲縺溘�縺九↑繝ｼ縺｣縺ｦ諤昴▲縺ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead02",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_05_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺ゅ▲�√蠕�▲縺ｦ縲∝調蟶鯉ｼ√繧ｹ繝医ャ繝暦ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-forward03",
               "FacialName":"face_worry_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_06_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺医▲縲√≠縲√�縺�ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-happy-glad02",
               "FacialName":"face_surprise_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_07_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺斐ａ繧薙∵･縺ｫ螟ｧ縺阪↑螢ｰ蜃ｺ縺励※縲�n縺昴％縺ｫ縲∬干縺後≠縺｣縺溘°繧峨▽縺�ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-nod05",
               "FacialName":"face_sad_03",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_08_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ゅ▲縲∵悽蠖薙□�√蜈ｨ辟ｶ豌励▼縺九↑縺九▲縺溘�n謨吶∴縺ｦ縺上ｌ縺ｦ縺ゅｊ縺後→縺",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod02",
               "FacialName":"face_surprise_03",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_09_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺弱ｊ縺弱ｊ雕上∪縺ｪ縺上※貂医ｓ窶ｦ窶ｦ縺ｧ縺ｪ縺�ｼ―n縺｡繧�▲縺ｨ闡峨▲縺ｱ雕上ｓ縺倥ｃ縺｣縺ｦ縺滂ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead08",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_10_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ｩ縲√←縺�＠繧医≧縲―n縺薙�蟄先椡繧後■繧�≧窶ｦ窶ｦ��ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-fidget01",
               "FacialName":"face_ worry_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_11_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺医▲縺ｨ窶ｦ窶ｦ縺ゅ√％繧後￥繧峨＞縺ｪ繧牙､ｧ荳亥､ｫ縲�n縺薙�遞ｮ鬘槭�闃ｱ縺ｯ荳亥､ｫ縺縺九ｉ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-trouble01",
               "FacialName":"face_smallmouth_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_12_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"繝帙Φ繝茨ｼ溘縺ｯ縺≫ｦ窶ｦ縺昴▲縺九＝縲∬憶縺九▲縺",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-forward02",
               "FacialName":"face_sparkling_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_13_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺昴ｌ縺ｫ縺励※繧ゅ√＆縺吶′縺�▲縺｡繧�ｓ�―n闃ｱ縺ｮ縺薙→縲√☆縺｣縺斐￥隧ｳ縺励＞縺ｭ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod06",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_14_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"繧医￥隕九°縺代ｋ闃ｱ縺縺九ｉ遏･縺｣縺ｦ縺溘□縺代□繧",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-shakehead01",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_15_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ｧ繧ゅ√％縺ｮ闃ｱ縺縺代§繧�↑縺上※縲―n縺�▲縺｡繧�ｓ縺�ｍ繧薙↑闃ｱ縺ｮ縺薙→遏･縺｣縺ｦ繧九〒縺励ｇ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod02",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_16_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"闃ｱ險闡峨→縺九∵�縺�▲縺｡繧�ｓ縺九ｉ\n縺溘￥縺輔ｓ謨吶ｏ縺｣縺溘ｈ縺ｭ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead08",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_17_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"窶ｦ窶ｦ縺昴ｓ縺ｪ縺薙→繧ゅ≠縺｣縺溘�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-nod01",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_18_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺�ｓ�√蜈･髯｢縺励※縺滓凾縺ｨ縺九∝ｮｶ縺ｧ蟇晁ｾｼ繧薙〒縺滓律縺ｨ縺九―n縺願ｦ玖�縺�↓縺�▲縺､繧り干謖√▲縺ｦ縺阪※縺上ｌ縺ｦ縲―n縺薙�闃ｱ縺ｯ縺ｭ繝ｼ縺｣縺ｦ隧ｱ縺励※縺上ｌ縺溘ｈ縺ｭ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod05",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_19_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺�ｓ縲よ≒縺九＠縺�↑",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-nod03",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_20_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺ゅｓ縺ｾ繧願ｱｪ闖ｯ縺ｪ縺ｮ縺ｯ雋ｷ縺医↑縺九▲縺溘°繧峨―n豈主屓闃ｱ險闡芽ｪｿ縺ｹ縺ｦ縲∽ｸ譛ｬ縺縺鷹∈繧薙〒窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-tilthead06",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_21_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺ｵ縺ｵ縲∬干螻九↓陦後￥縺ｮ讌ｽ縺励°縺｣縺溘↑縲�n縺ゅ�鬆��蟆丞ｭｦ逕溘□縺｣縺溘°繧峨∝ｺ励�莠ｺ縺後が繝槭こ縺励※縺上ｌ縺溘ｊ縺励※",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-glad01",
               "FacialName":"face_smile_03",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_22_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"繧｢繧ｿ繧ｷ縺御ｻ企髯｢縺励※蜈�ｰ励〒縺�ｉ繧後ｋ縺ｮ繧ゅ―n縺�▲縺｡繧�ｓ縺ｮ闃ｱ縺ｮ縺翫°縺偵°繧ゑｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead02",
               "FacialName":"face_surprise_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_23_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"繧ゅ≧縲∝調蟶後�螟ｧ縺偵＆縺縺ｪ窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-tilthead01",
               "FacialName":"face_sad_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_24_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ｵ縺ｵ縺｣縲ょｮ溘�縺ｭ縲√＞縺｣縺｡繧�ｓ縺後￥繧後◆闃ｱ縲―n謚ｼ縺苓干縺ｫ縺励※縺ｨ縺｣縺ｦ縺ゅｋ縺ｮ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-normal-tilthead02",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_25_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺茨ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-tilthead03",
               "FacialName":"face_surprise_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_26_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺昴�闃ｱ繧定ｦ九ｋ縺ｨ縺ｭ縲―n霎帙＞豌玲戟縺｡繧ゅ☆繝ｼ縺｣縺ｦ縺ｪ縺上↑縺｣縺ｦ縺�￥繧薙□繧茨ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead03",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_27_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"蜥ｲ蟶娯ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-tilthead04",
               "FacialName":"face_shy_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_28_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"窶ｦ窶ｦ縺ゅゅ◎縺�＞縺医�縲∝ｭｦ譬｡縺ｧ閧ｲ縺ｦ縺溘い繧ｵ繧ｬ繧ｪ繧箪n謖√▲縺ｦ縺阪※繧ゅｉ縺｣縺溘％縺ｨ繧ゅ≠縺｣縺溘ｈ縺ｭ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod06",
               "FacialName":"face_surprise_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_29_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺ゅよ､肴惠驩｢縺ｫ蜈･縺｣縺溯干縺ｯ邵∬ｵｷ縺梧が縺�↑繧薙※遏･繧峨↑縺上※\n縺昴�縺ｾ縺ｾ謖√▲縺ｦ陦後▲縺｡繧�▲縺溘ｓ縺繧医�窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-nod03",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_30_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ゅ�譎ゅ∫恚隴ｷ蟶ｫ縺輔ｓ縺弱ｇ縺｣縺ｨ縺励◆鬘斐＠縺ｦ縺溘ｈ縺ｭ縲�n繧｢繧ｿ繧ｷ莉翫〒繧ゅ�縺｣縺阪ｊ隕壹∴縺ｦ繧九ｈ繝ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead04",
               "FacialName":"face_shy_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_31_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ｧ繧ゅ√◎縺ｮ繧｢繧ｵ繧ｬ繧ｪ縺ｮ遞ｮ縺ｧ縲―n縺ｻ縺ｪ縺｡繧�ｓ繧�＠縺ｻ縺｡繧�ｓ縺ｨ荳邱偵↓\n縺�■縺ｫ繧｢繧ｵ繧ｬ繧ｪ縺ｮ蠎ｭ繧剃ｽ懊▲縺溘ｈ縺ｭ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod02",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_32_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"窶ｦ窶ｦ縺�ｓ縲ゅ∩繧薙↑縺ｧ蜥ｲ蟶後�螳ｶ縺ｫ縺企が鬲斐＠縺ｦ縲―n讒伜ｭ舌ｂ隕九↓陦後▲縺溘↑",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-nod03",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_33_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺昴≧縺昴≧�―n縺ｧ繧ゅ√い繧ｿ繧ｷ縺御ｸ騾ｱ髢薙￥繧峨＞豌ｴ繧�ｊ縺ｧ縺阪↑縺上※窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod02",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_34_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"莉墓婿縺ｪ縺�ｈ縲∽ｽ楢ｪｿ謔ｪ縺九▲縺溘ｓ縺ｧ縺励ｇ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-shakehead01",
               "FacialName":"face_worry_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_35_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺ｧ繧ゅ√◎縺ｮ縺帙＞縺ｧ繧｢繧ｵ繧ｬ繧ｪ縺悟�豌励↑縺上＠縺｡繧�▲縺ｦ窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-fidget01",
               "FacialName":"face_sad_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_36_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"縺ゅ�譎ゅ�縲∝調蟶後′縺吶＃縺剰誠縺｡霎ｼ繧薙〒繧九°繧峨▲縺ｦ縲―n�謎ｺｺ縺ｧ鬆大ｼｵ縺｣縺ｦ縺贋ｸ冶ｩｱ縺励◆縺ｪ縺≫ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-tilthead05",
               "FacialName":"face_smile_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_37_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺昴≧�√縺ｳ縺｣縺上ｊ縺励◆繧薙□繧医∽ｹ�＠縺ｶ繧翫↓縺雁ｺｭ縺ｫ蜃ｺ縺溘ｉ\n蜈�ｰ励↑縺九▲縺溘�縺壹�繧｢繧ｵ繧ｬ繧ｪ縺後ヴ繝ｳ繝斐Φ縺励※繧九ｓ縺繧ゅｓ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-happy-forward02",
               "FacialName":"face_sparkling_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_38_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺頑ｯ阪＆繧薙↓閨槭＞縺溘ｉ縲�ｼ謎ｺｺ縺後♀荳冶ｩｱ縺励※縺上ｌ縺溘▲縺ｦ窶ｦ窶ｦ\n繧｢繧ｿ繧ｷ縲∝ｬ峨＠縺上※縺雁ｺｭ縺ｧ豕｣縺�■繧�▲縺溘ｓ縺",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-nod02",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_39_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"縺医∈縺ｸ縲√い繧ｿ繧ｷ縺ｮ螟ｧ莠九↑螟ｧ莠九↑諤昴＞蜃ｺ�",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-glad01",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_40_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"窶ｦ窶ｦ縺ｾ縺滂ｼ比ｺｺ縺ｧ荳邱偵↓驕翫ｓ縺繧翫〒縺阪ｋ縺九↑縺",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-tilthead04",
               "FacialName":"face_smile_02",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_41_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"窶ｦ窶ｦ窶ｦ窶ｦ",
         "TalkTention":0,
         "LipSync":2,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-normal-tilthead02",
               "FacialName":"face_sad_03",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_42_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":2
            }
         ],
         "WindowDisplayName":"蜥ｲ蟶",
         "Body":"窶ｦ窶ｦ縺�ｓ�√縺ｨ縺ｫ縺九￥繧�▲縺ｦ縺ｿ縺ｪ縺�→縺繧医��―n縺ｨ縺�≧繧上￠縺ｧ縲∵叛隱ｲ蠕後―n縺ｻ縺ｪ縺｡繧�ｓ縺ｨ縺励⊇縺｡繧�ｓ縺ｫ螢ｰ縺九￠縺ｦ縺ｿ縺ｪ縺�ｼ",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":2,
               "MotionName":"w-cute-glad03",
               "FacialName":"face_smile_04",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":2,
               "VoiceId":"voice_card_01_01a_43_02",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":0,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      },
      {
         "TalkCharacters":[
            {
               "Character2dId":1
            }
         ],
         "WindowDisplayName":"荳豁",
         "Body":"窶ｦ窶ｦ縺�ｓ縲ゅ◎縺�＠縺ｦ縺ｿ繧医▲縺",
         "TalkTention":0,
         "LipSync":1,
         "MotionChangeFrom":1,
         "Motions":[
            {
               "Character2dId":1,
               "MotionName":"w-cool-tilthead01",
               "FacialName":"face_smallmouth_01",
               "TimingSyncValue":0.0
            }
         ],
         "Voices":[
            {
               "Character2dId":1,
               "VoiceId":"voice_card_01_01a_44_01",
               "Volume":1.0
            }
         ],
         "Speed":0.0,
         "FontSize":0,
         "WhenFinishCloseWindow":1,
         "RequirePlayEffect":0,
         "EffectReferenceIdx":0,
         "RequirePlaySound":0,
         "SoundReferenceIdx":0
      }
   ],
   "LayoutData":[
      {
         "Type":2,
         "SideFrom":4,
         "SideFromOffsetX":0.0,
         "SideTo":4,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"01ichika_normal",
         "MotionName":"w-normal-tilthead05",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":3,
         "SideFrom":4,
         "SideFromOffsetX":0.0,
         "SideTo":4,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"",
         "FacialName":"",
         "MoveSpeedType":0
      },
      {
         "Type":2,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"",
         "FacialName":"",
         "MoveSpeedType":0
      },
      {
         "Type":2,
         "SideFrom":7,
         "SideFromOffsetX":0.0,
         "SideTo":7,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"02saki_normal",
         "MotionName":"w-cute-glad01",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-normal-nod06",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-normal-tilthead05",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-nod05",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-forward03",
         "FacialName":"face_surprise_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead07",
         "FacialName":"face_sad_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-cool-nod01",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-nod02",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-normal-nod06",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead03",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-glad04",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead07",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-normal-nod06",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-cool-nod02",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-normal-nod06",
         "FacialName":"face_surprise_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-normal-nod05",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-nod02",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead02",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-cool-tilthead03",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-glad01",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead07",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-cool-trouble01",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-shakehead02",
         "FacialName":"face_sad_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-normal-shy01",
         "FacialName":"face_smile_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-nod01",
         "FacialName":"face_sparkling_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-glad05",
         "FacialName":"face_sparkling_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-tilthead02",
         "FacialName":"face_smile_04",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"w-cute-forward02",
         "FacialName":"face_sparkling_01",
         "MoveSpeedType":0
      },
      {
         "Type":0,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"w-happy-nod01",
         "FacialName":"face_smile_02",
         "MoveSpeedType":0
      },
      {
         "Type":3,
         "SideFrom":3,
         "SideFromOffsetX":0.0,
         "SideTo":3,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":1,
         "CostumeType":"",
         "MotionName":"",
         "FacialName":"",
         "MoveSpeedType":0
      },
      {
         "Type":3,
         "SideFrom":7,
         "SideFromOffsetX":0.0,
         "SideTo":7,
         "SideToOffsetX":0.0,
         "DepthType":0,
         "Character2dId":2,
         "CostumeType":"",
         "MotionName":"",
         "FacialName":"",
         "MoveSpeedType":0
      }
   ],
   "SpecialEffectData":[
      {
         "EffectType":8,
         "StringVal":"螳ｮ逶雁揩螂ｳ蟄仙ｭｦ蝨偵荳ｭ蠎ｭ",
         "StringValSub":"",
         "Duration":0.0,
         "IntVal":0
      },
      {
         "EffectType":2,
         "StringVal":"",
         "StringValSub":"",
         "Duration":2.5,
         "IntVal":0
      }
   ],
   "SoundData":[
      {
         "PlayMode":0,
         "Bgm":"bgm00000",
         "Se":"",
         "Volume":1.0,
         "SeBundleName":"",
         "Duration":1.5
      },
      {
         "PlayMode":0,
         "Bgm":"bgm00024",
         "Se":"",
         "Volume":1.0,
         "SeBundleName":"",
         "Duration":1.5
      },
      {
         "PlayMode":0,
         "Bgm":"bgm00000",
         "Se":"",
         "Volume":1.0,
         "SeBundleName":"",
         "Duration":2.5
      }
   ],
   "NeedBundleNames":[
      "scenario/background/bg_a002201"
   ],
   "IncludeSoundDataBundleNames":[
      
   ]
}"å"
}